//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe_MVC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wadrobe_DBEntities : DbContext
    {
        public Wadrobe_DBEntities()
            : base("name=Wadrobe_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accessory> Accessories { get; set; }
        public DbSet<Bottom> Bottoms { get; set; }
        public DbSet<Sho> Shoes { get; set; }
        public DbSet<Top> Tops { get; set; }
    }
}
